
STAGE: 'train'
DATA:
  PATH: ./dataset/emgleap/003/S1
  SEGMENT_LENGTH: 200
  STRIDE: 4
  FILTER: True
  EXP_SETUP: 'exp0'
  ICA: False

MODEL:
  NAME: 'vvit'

SOLVER:
    BATCH_SIZE: 32
    NUM_EPOCHS: 100
    LR: 0.000001
    WEIGHT_DECAY: 0.0001
    OPTIMIZER: 'adam'
    METRIC: 'MAE'
    DEVICE: 'cuda:0'

DEBUG: False

